import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

// Add CMS tables
export const cmsPages = sqliteTable('cms_pages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  content: text('content'),
  metaDescription: text('meta_description'),
  metaKeywords: text('meta_keywords'),
  status: text('status').notNull().default('draft'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  createdBy: integer('created_by'),
  updatedBy: integer('updated_by'),
});

export const cmsMedia = sqliteTable('cms_media', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  filename: text('filename').notNull(),
  originalFilename: text('original_filename').notNull(),
  fileUrl: text('file_url').notNull(),
  fileType: text('file_type').notNull(),
  mimeType: text('mime_type').notNull(),
  fileSize: integer('file_size').notNull(),
  altText: text('alt_text'),
  uploadedBy: integer('uploaded_by'),
  uploadedAt: integer('uploaded_at', { mode: 'timestamp' }).notNull(),
});

export const cmsTours = sqliteTable('cms_tours', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  category: text('category').notNull(),
  tags: text('tags', { mode: 'json' }),
  durationDays: integer('duration_days'),
  durationNights: integer('duration_nights'),
  priceFromNgn: integer('price_from_ngn'),
  priceFromUsd: integer('price_from_usd'),
  shortDescription: text('short_description'),
  fullDescription: text('full_description'),
  highlights: text('highlights', { mode: 'json' }),
  inclusions: text('inclusions', { mode: 'json' }),
  exclusions: text('exclusions', { mode: 'json' }),
  itinerary: text('itinerary', { mode: 'json' }),
  accommodationExamples: text('accommodation_examples', { mode: 'json' }),
  seasonality: text('seasonality'),
  visaNotes: text('visa_notes'),
  addOns: text('add_ons', { mode: 'json' }),
  cancellationTerms: text('cancellation_terms'),
  gallery: text('gallery', { mode: 'json' }),
  whatsappPrefill: text('whatsapp_prefill'),
  status: text('status').notNull().default('draft'),
  featured: integer('featured').default(0),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  createdBy: integer('created_by'),
  updatedBy: integer('updated_by'),
});

export const cmsShortlets = sqliteTable('cms_shortlets', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  location: text('location').notNull(),
  area: text('area'),
  city: text('city'),
  state: text('state'),
  nearby: text('nearby'),
  propertyType: text('property_type').notNull(),
  pricePerNightNgn: integer('price_per_night_ngn'),
  pricePerNightUsd: integer('price_per_night_usd'),
  bedrooms: integer('bedrooms'),
  bathrooms: integer('bathrooms'),
  maxGuests: integer('max_guests'),
  description: text('description'),
  amenities: text('amenities', { mode: 'json' }),
  features: text('features', { mode: 'json' }),
  checkIn: text('check_in'),
  checkOut: text('check_out'),
  minimumStay: text('minimum_stay'),
  cancellationPolicy: text('cancellation_policy'),
  deposit: text('deposit'),
  houseRules: text('house_rules', { mode: 'json' }),
  gallery: text('gallery', { mode: 'json' }),
  rating: text('rating'),
  reviewsCount: integer('reviews_count').default(0),
  hostName: text('host_name'),
  hostResponseTime: text('host_response_time'),
  whatsappPrefill: text('whatsapp_prefill'),
  status: text('status').notNull().default('available'),
  featured: integer('featured').default(0),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  createdBy: integer('created_by'),
  updatedBy: integer('updated_by'),
});